version: '2'
services:
    jhipstersampleapplication180608-app:
        image: jhipstersampleapplication180608
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication180608-mysql:3306/jhipstersampleapplication180608?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplication180608-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication180608-mysql
